name: Docker Build

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
    secrets:
      registry-auth:
        description: YAML list of additional registry credentials for private base images
        required: false
    outputs:
      image:
        description: Multi-platform image tag
        value: ${{ jobs.merge.outputs.image }}
      image-arm64:
        description: ARM64 image digest reference
        value: ${{ jobs.build.outputs.image-arm64 }}
      image-x64:
        description: x64 image digest reference
        value: ${{ jobs.build.outputs.image-x64 }}

env:
  BUILD_SUFFIX: -build-${{ github.run_id }}_${{ github.run_attempt }}
  DOCKER_METADATA_SET_OUTPUT_ENV: 'true'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    outputs:
      image-arm64: ${{ steps.gen-output.outputs.image-arm64 }}
      image-x64: ${{ steps.gen-output.outputs.image-x64 }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-24.04
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to container registries
        uses: docker/login-action@v4
        with:
          registry-auth: |
            - registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}
            ${{ secrets.registry-auth }}

      - id: build-meta
        name: Prepare Docker metadata
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.image }}
          tags: type=sha,suffix=${{ env.BUILD_SUFFIX }}

      - id: cache-meta
        name: Fetch build cache metadata
        uses: docker/metadata-action@v6
        with:
          images: ${{ inputs.image }}
          tags: type=raw,value=buildcache-${{ runner.arch }}

      - id: get-registry
        name: Get the sanitized registry name
        run: |
          echo "registry=$(echo '${{ steps.build-meta.outputs.tags }}' | cut -f1 -d:)" | tee -a "$GITHUB_OUTPUT"

      - id: build
        name: Build/push the arch-specific image
        uses: docker/build-push-action@v7
        with:
          platforms: ${{ matrix.platform }}
          cache-from: type=registry,ref=${{ steps.cache-meta.outputs.tags }}
          cache-to: type=registry,ref=${{ steps.cache-meta.outputs.tags }},mode=max
          labels: ${{ steps.build-meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          tags: ${{ steps.get-registry.outputs.registry }}
          outputs: type=image,push-by-digest=true,push=true

      - id: gen-output
        name: Write arch-specific image digest to outputs
        run: |
          echo "image-${RUNNER_ARCH,,}=${{ steps.get-registry.outputs.registry }}@${{ steps.build.outputs.digest }}" | tee -a "$GITHUB_OUTPUT"

  merge:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        name: Generate tag for the app image
        uses: docker/metadata-action@v6
        env:
          DOCKER_METADATA_SET_OUTPUT_ENV: 'true'
        with:
          images: ${{ inputs.image }}
          tags: type=sha,suffix=-build-${{ github.run_id }}_${{ github.run_attempt }}

      - name: Retag and push the multi-platform image
        run: |
          docker buildx imagetools create \
            --tag "$DOCKER_METADATA_OUTPUT_TAGS" \
            "${{ needs.build.outputs.image-arm64 }}" "${{ needs.build.outputs.image-x64 }}"
